version: '3.8'

services:
  trellis:
    runtime: nvidia  # Explicitly use NVIDIA runtime
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: ${GPU_COUNT:-all}
              capabilities: [gpu]
    ports:
      # Explicitly bind to all interfaces for remote access
      - "0.0.0.0:${HOST_PORT:-8501}:${APP_PORT:-8501}"
    volumes:
      # Mount source code for hot reloading in development
      # Hot-reloadable: UI code and main app
      - ./app.py:/app/app.py
      - ./webui:/app/webui
      - ./docs:/app/docs
      - ./assets:/app/assets
      # NOT mounted: trellis/ (installed package - rebuild for changes)
      # NOT mounted: extensions/ (compiled C++ code)
    environment:
      # Enable hot reloading and better development experience
      - STREAMLIT_SERVER_HEADLESS=false
      # Explicitly bind Streamlit to all interfaces
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    stdin_open: true
    tty: true
    networks:
      - default
