version: '3.8'

services:
  trellis:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Override these in .env file or here
        CUDA_VERSION: ${CUDA_VERSION:-12.1.0}
        CUDNN_VERSION: ${CUDNN_VERSION:-8}
        UBUNTU_VERSION: ${UBUNTU_VERSION:-22.04}
        PYTHON_VERSION: ${PYTHON_VERSION:-3.10}
        POETRY_VERSION: ${POETRY_VERSION:-1.8.3}
        KAOLIN_VERSION: ${KAOLIN_VERSION:-0.17.0}
        KAOLIN_INDEX_URL: ${KAOLIN_INDEX_URL:-https://nvidia-kaolin.s3.us-east-2.amazonaws.com/torch-2.4.0_cu121.html}
        TORCH_CUDA_ARCH_LIST: ${TORCH_CUDA_ARCH_LIST:-7.0 7.5 8.0 8.6 8.9 9.0}
        APP_USER: ${APP_USER:-appuser}
        APP_UID: ${APP_UID:-1000}
        APP_PORT: ${APP_PORT:-8501}
        CACHE_DIR: ${CACHE_DIR:-/home/appuser/.cache}
        HF_CACHE_DIR: ${HF_CACHE_DIR:-/home/appuser/.cache/huggingface}
        REMBG_CACHE_DIR: ${REMBG_CACHE_DIR:-/home/appuser/.u2net}
        TRELLIS_OUTPUT_DIR: ${TRELLIS_OUTPUT_DIR:-/tmp/Trellis-demo}
    image: trellis-box:latest
    container_name: trellis-box
    ports:
      - "${HOST_PORT:-8501}:${APP_PORT:-8501}"
    volumes:
      # Persist model cache between runs
      - ${CACHE_VOLUME:-trellis-cache}:${CACHE_DIR:-/home/appuser/.cache}
      # Persist Hugging Face cache
      - ${HF_CACHE_VOLUME:-huggingface-cache}:${HF_CACHE_DIR:-/home/appuser/.cache/huggingface}
      # Persist rembg model cache
      - ${REMBG_CACHE_VOLUME:-rembg-cache}:${REMBG_CACHE_DIR:-/home/appuser/.u2net}
      # Persist generated outputs (bind mount to local directory)
      - ${OUTPUTS_HOST_DIR:-./outputs}:${TRELLIS_OUTPUT_DIR:-/tmp/Trellis-demo}
    environment:
      # Optional: Add any runtime environment variables here
      - CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-all}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: ${GPU_COUNT:-all}
              capabilities: [gpu]
    stdin_open: true
    tty: true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python3", "-c", "import requests; requests.get('http://localhost:${APP_PORT:-8501}/_stcore/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  trellis-cache:
    driver: local
  huggingface-cache:
    driver: local
  rembg-cache:
    driver: local

