version: '3.8'

services:
  trellis:
    volumes:
      # Mount source code for hot reloading in development
      # Hot-reloadable: UI code and main app
      - ./app.py:/app/app.py
      - ./webui:/app/webui
      - ./docs:/app/docs
      - ./assets:/app/assets
      # NOT mounted: trellis/ (installed package - rebuild for changes)
      # NOT mounted: extensions/ (compiled C++ code)
    environment:
      # Enable hot reloading and better development experience
      - STREAMLIT_SERVER_HEADLESS=false
    stdin_open: true
    tty: true
