version: '3.8'

services:
  trellis:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Override these in .env file or here
        CUDA_VERSION: ${CUDA_VERSION:-12.3.2}
        CUDNN_VERSION: ${CUDNN_VERSION:-9}
        UBUNTU_VERSION: ${UBUNTU_VERSION:-22.04}
        PYTHON_VERSION: ${PYTHON_VERSION:-3.10}
        POETRY_VERSION: ${POETRY_VERSION:-1.8.3}
        KAOLIN_VERSION: ${KAOLIN_VERSION:-0.17.0}
        KAOLIN_INDEX_URL: ${KAOLIN_INDEX_URL:-https://nvidia-kaolin.s3.us-east-2.amazonaws.com/torch-2.4.0_cu121.html}
        TORCH_CUDA_ARCH_LIST: ${TORCH_CUDA_ARCH_LIST:-7.0 7.5 8.0 8.6 8.9 9.0}
        APP_USER: ${APP_USER:-appuser}
        APP_UID: ${APP_UID:-1000}
        APP_PORT: ${APP_PORT:-8501}
        STREAMLIT_SERVER_ADDRESS: ${STREAMLIT_SERVER_ADDRESS:-0.0.0.0}
        STREAMLIT_SERVER_HEADLESS: ${STREAMLIT_SERVER_HEADLESS:-true}
        CACHE_DIR: ${CACHE_DIR:-/home/appuser/.cache}
        HOST_CACHE_DIR: ${HOST_CACHE_DIR:-~/.cache/trellis}
        HOST_HF_CACHE_DIR: ${HOST_HF_CACHE_DIR:-~/.cache/huggingface}
        HOST_REMBG_CACHE_DIR: ${HOST_REMBG_CACHE_DIR:-~/.cache/rembg}
        HF_CACHE_DIR: ${HF_CACHE_DIR:-/home/appuser/.cache/huggingface}
        REMBG_CACHE_DIR: ${REMBG_CACHE_DIR:-/app/rembg_cache}
        TRELLIS_OUTPUT_DIR: ${TRELLIS_OUTPUT_DIR:-/app/outputs}
    image: trellis-box:latest
    container_name: trellis-box
    ports:
      - "${HOST_PORT:-8501}:${APP_PORT:-8501}"
    volumes:
      # Persist model cache between runs (use bind mounts for better compatibility)
      - ${HOST_CACHE_DIR:-~/.cache/trellis}:${CACHE_DIR:-/home/appuser/.cache}
      # Persist Hugging Face cache
      - ${HOST_HF_CACHE_DIR:-~/.cache/huggingface}:${HF_CACHE_DIR:-/home/appuser/.cache/huggingface}
      # Persist rembg model cache to host
      - ${HOST_REMBG_CACHE_DIR:-./rembg_cache}:${REMBG_CACHE_DIR:-/app/rembg_cache}
      # Persist generated outputs to host
      - ${OUTPUTS_HOST_DIR:-./outputs}:${TRELLIS_OUTPUT_DIR:-/app/outputs}
    environment:
      # Streamlit configuration
      - STREAMLIT_SERVER_PORT=${APP_PORT:-8501}
      - STREAMLIT_SERVER_ADDRESS=${STREAMLIT_SERVER_ADDRESS:-0.0.0.0}
      - STREAMLIT_SERVER_HEADLESS=${STREAMLIT_SERVER_HEADLESS:-true}
      # Cache directories - ensure models persist across container restarts
      - CACHE_DIR=${CACHE_DIR:-/home/appuser/.cache}
      - HF_HOME=${HF_CACHE_DIR:-/home/appuser/.cache/huggingface}
      - HUGGINGFACE_HUB_CACHE=${HF_CACHE_DIR:-/home/appuser/.cache/huggingface}
      - TRANSFORMERS_CACHE=${HF_CACHE_DIR:-/home/appuser/.cache/huggingface}
      - U2NET_HOME=${REMBG_CACHE_DIR:-/app/rembg_cache}
      - TRELLIS_OUTPUT_DIR=${TRELLIS_OUTPUT_DIR:-/app/outputs}
      # CUDA configuration
      - CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-all}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: ${GPU_COUNT:-all}
              capabilities: [gpu]
    stdin_open: true
    tty: true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python3", "-c", "import requests; requests.get('http://localhost:${APP_PORT:-8501}/_stcore/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  trellis-cache:
    driver: local
  huggingface-cache:
    driver: local
  rembg-cache:
    driver: local
  trellis-outputs:
    driver: local

