#!/bin/bash

set -e

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT_DIR"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

INSTALL_MODE="${TRELLIS_INSTALL_MODE:-auto}"
PYTHON_REQUESTED="${PYTHON_BIN:-}"
VENV_DIR="${TRELLIS_VENV_DIR:-.venv}"
REINSTALL=false

print_status() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1" >&2
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

usage() {
    cat <<EOF
TRELLIS installer

Usage: ./install.sh [options]

Options:
  --portable       Install local CPU/macOS portable environment
  --docker         Configure Docker/CUDA mode without creating a Python venv
  --python PATH    Python executable for portable mode
  --venv PATH      Virtual environment directory (default: .venv)
  --reinstall      Reinstall portable Python dependencies
  --help           Show this help
EOF
}

while [ "$#" -gt 0 ]; do
    case "$1" in
        --portable)
            INSTALL_MODE="portable"
            ;;
        --docker)
            INSTALL_MODE="docker"
            ;;
        --python)
            shift
            PYTHON_REQUESTED="${1:-}"
            ;;
        --venv)
            shift
            VENV_DIR="${1:-}"
            ;;
        --reinstall)
            REINSTALL=true
            ;;
        --help|-h)
            usage
            exit 0
            ;;
        *)
            print_error "Unknown option: $1"
            usage
            exit 1
            ;;
    esac
    shift
done

detect_mode() {
    if [ "$INSTALL_MODE" != "auto" ]; then
        echo "$INSTALL_MODE"
        return
    fi

    if [ "$(uname -s)" = "Darwin" ]; then
        echo "portable"
        return
    fi

    if command -v docker > /dev/null 2>&1 && command -v nvidia-smi > /dev/null 2>&1; then
        echo "docker"
        return
    fi

    echo "portable"
}

find_python() {
    if [ -n "$PYTHON_REQUESTED" ]; then
        echo "$PYTHON_REQUESTED"
        return
    fi

    for candidate in python3.10 python3.11 python3.12 python3; do
        if command -v "$candidate" > /dev/null 2>&1; then
            echo "$candidate"
            return
        fi
    done

    return 1
}

check_python_version() {
    local python_bin="$1"
    "$python_bin" - <<'PY'
import sys
version = sys.version_info
if version < (3, 10) or version >= (3, 13):
    raise SystemExit(f"Python >=3.10,<3.13 is required; found {sys.version.split()[0]}")
PY
}

detect_cpu_threads() {
    if [ -n "${TRELLIS_CPU_THREADS:-}" ]; then
        echo "$TRELLIS_CPU_THREADS"
        return
    fi

    if [ "$(uname -s)" = "Darwin" ] && command -v sysctl > /dev/null 2>&1; then
        sysctl -n hw.physicalcpu 2>/dev/null && return
    fi

    getconf _NPROCESSORS_ONLN 2>/dev/null || echo 4
}

write_env() {
    local mode="$1"
    local python_bin="$2"
    local cpu_threads
    cpu_threads="$(detect_cpu_threads)"

    {
        echo "# Generated by ./install.sh. Local machine settings; do not commit."
        echo "TRELLIS_RUNTIME=${mode}"
        echo "TRELLIS_CPU_THREADS=${cpu_threads}"
        echo "OMP_NUM_THREADS=${OMP_NUM_THREADS:-$cpu_threads}"
        echo "MKL_NUM_THREADS=${MKL_NUM_THREADS:-$cpu_threads}"
        echo "VECLIB_MAXIMUM_THREADS=${VECLIB_MAXIMUM_THREADS:-$cpu_threads}"
        echo "NUMEXPR_NUM_THREADS=${NUMEXPR_NUM_THREADS:-$cpu_threads}"
        echo "TORCH_NUM_THREADS=${TORCH_NUM_THREADS:-$cpu_threads}"
        if [ "$mode" = "portable" ]; then
            echo "TRELLIS_DEVICE=${TRELLIS_DEVICE:-cpu}"
            echo "SPARSE_BACKEND=${SPARSE_BACKEND:-torch}"
            echo "ATTN_BACKEND=${ATTN_BACKEND:-sdpa}"
            echo "PYTHON_BIN=${python_bin}"
            echo "TRELLIS_OUTPUT_DIR=./outputs"
            echo "U2NET_HOME=./rembg_cache"
        else
            echo "TRELLIS_DEVICE=${TRELLIS_DEVICE:-cuda}"
        fi
    } > .trellis.env
}

install_portable() {
    local python_bin
    python_bin="$(find_python)" || {
        print_error "No Python executable found. Install Python 3.10, 3.11, or 3.12."
        exit 1
    }

    print_status "Using Python: $python_bin"
    check_python_version "$python_bin"

    if [ ! -d "$VENV_DIR" ]; then
        print_status "Creating virtual environment: $VENV_DIR"
        "$python_bin" -m venv "$VENV_DIR"
    else
        print_status "Using existing virtual environment: $VENV_DIR"
    fi

    local venv_python="$VENV_DIR/bin/python"
    if [ ! -x "$venv_python" ]; then
        print_error "Virtual environment Python not found: $venv_python"
        exit 1
    fi

    print_status "Upgrading pip tooling"
    "$venv_python" -m pip install --upgrade pip setuptools wheel

    if [ "$REINSTALL" = true ]; then
        print_status "Reinstalling portable dependencies"
        "$venv_python" -m pip install --upgrade --force-reinstall -r requirements.macos.txt
    else
        print_status "Installing portable dependencies"
        "$venv_python" -m pip install -r requirements.macos.txt
    fi

    print_status "Verifying portable Python environment"
    "$venv_python" - <<'PY'
import importlib

required = [
    "streamlit",
    "torch",
    "torchvision",
    "easydict",
    "rembg",
    "skimage",
    "trimesh",
    "plyfile",
]

missing = []
for module in required:
    try:
        importlib.import_module(module)
    except Exception as exc:
        missing.append(f"{module}: {exc}")

if missing:
    raise SystemExit("Portable environment verification failed:\n" + "\n".join(missing))
PY

    mkdir -p outputs rembg_cache
    write_env "portable" "$venv_python"

    print_success "Portable TRELLIS environment installed"
    print_status "Run: ./trellis.sh run --dev"
}

install_docker() {
    print_status "Configuring Docker/CUDA mode"

    if ! command -v docker > /dev/null 2>&1; then
        print_error "Docker is not installed or not on PATH."
        exit 1
    fi

    if ! command -v nvidia-smi > /dev/null 2>&1; then
        print_warning "nvidia-smi was not found. Docker mode is configured, but GPU checks may fail."
    fi

    mkdir -p outputs rembg_cache
    write_env "docker" ""

    print_success "Docker/CUDA TRELLIS mode configured"
    print_status "Run: ./trellis.sh run"
}

MODE="$(detect_mode)"
case "$MODE" in
    portable)
        install_portable
        ;;
    docker)
        install_docker
        ;;
    *)
        print_error "Unknown install mode: $MODE"
        exit 1
        ;;
esac
