[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[theme]
# Use base theme that respects user's browser theme preference
base = "light"
primaryColor = "#667eea"
# backgroundColor will follow user's system theme
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[client]
showErrorDetails = true
toolbarMode = "minimal"

[ui]
hideTopBar = false
hideSidebarNav = false

